import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Quantico } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const quantico = Quantico({
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-quantico",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${quantico.variable} antialiased min-h-dvh min-w-dvw flex flex-col bg-light`}
      >
        <Toaster />
        <main className="flex-1 flex font-mono">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
